### PR TITLE
Project title now redirects to Home page

### PR DESCRIPTION
**Pull request by ananthvgb2003**
I have solved issue #11. The Project title now redirects to the Home page. Due to this, suppose a user chooses multiple tags, so if he/she wants to reset all tags at once, clicking on the Project title will do the same.

### CODE REVIEW

**Comment by Savio629** [comment]
@ananthvgb2003 Also can you add a Clear button which will work the same, as it would easier to know if someone wants to clear all the tags....

**Comment by ananthvgb2003** [comment]
yeah that would be better, @Savio629 . Will work on it.

**Comment by ananthvgb2003** [comment]
@Savio629 I implemented your suggestion. Please review it and inform if any further change is required.

**Review by Savio629 — APPROVED** [review]

**Comment by Savio629** [comment]
LGTM

**Pull request merged**
